### ISSUE TITLE
// TODO: documentation! 

### ISSUE THREAD

**Issue by iamstarkov** [kinda/kinda-log#1]
just do it ftw

**Comment by mvila** [comment]
I'm sorry but 1) this module is still very unstable (lot of API changes) and 2) I don't have enough time now to work on the documentation.

**Comment by iamstarkov** [comment]
okie

**Comment by mvila** [comment]
This module has been renamed to [UniversalLog](https://github.com/mvila/universal-log) and there is now a documentation! :)
